import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='jp'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-zen bg-mainBackgroundColor text-mainFontColor max-w-xs sm:max-w-2xl lg:max-w-4xl xl:max-w-5xl mx-auto`}
      >
        <Header />
        <main>{children}</main>
        <Footer />
        {/* <br/>
      <br/>
      <div className='w-5xl border border-red-500 mx-auto'>width test</div>
      <br/>
      <div className="max-w-5xl border border-red-500 mx-auto">max width test</div>
      <br/>
      <div className="mx-100 border border-red-500 mx-auto">margin test</div>
      <br/>
      <div className='w-[40%] border border-red-500 mx-auto'>40% width test</div>
      <br/>
      <div className='w-[60%] border border-red-500 mx-auto'>60% width test</div>
      <br/>
      <div className='w-[80%] border border-red-500 mx-auto'>80% width test</div>
      <br/>
      <br/> */}
      </body>
    </html>
  );
}
